version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 29032006
      POSTGRES_DB: music
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/music
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 29032006
      SERVER_PORT: 8082
    depends_on:
      - db
    volumes:
      - ./csv:/app/csv 

  webapp:
    build: ./python
    ports:
      - "7300:7300"
    depends_on:
      - db
      - app