version: '3.8'
services:

  app:
    build: .
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://music.c1i8k6kqwojb.eu-west-2.rds.amazonaws.com:5432/initial_db?sslmode=require
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 29032006
      SERVER_PORT: 8082
    volumes:
      - ./csv:/app/csv 

  webapp:
    build: ./python
    ports:
      - "7300:7300"
    depends_on:
      - app