version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 29032006
      POSTGRES_DB: music
    networks:
      - internal_network

  app:
    build: .
    networks:
      - internal_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/music
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 29032006
      SERVER_PORT: 8082
    depends_on:
      - db
    volumes:
      - ./csv:/app/csv 

  webapp:
    build: ./python
    ports:
      - "7300:7300"
    depends_on:
      - db
      - app

  webserver:
    build: ./apache

    ports:
      - "80:80"
      - "443:443"

networks:
  internal_network:
    internal: true